from .user import User
from .admin import Admin
from .staff import Staff
from .course import Course
from .programme import Programme
from .courseInstructor import CourseInstructor
from .courseProgramme import CourseProgramme
from .semester import Semester
from .courseAssessment import CourseAssessment
