name: Unit & Integration Tests

on:
  push:
    branches: ["main", "dev", "prod", "test"]
  pull_request:
    branches: ["main", "dev", "prod", "test"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
